// Daily Motivation Quotes for Training Days
export const motivationQuotes = [
    "今天的汗水，是明天的榮耀！",
    "每一步都在靠近終點線！",
    "鐵人精神，永不放棄！",
    "痛苦是暫時的，榮耀是永恆的！",
    "相信過程，成就自己！",
    "你比你想像的更強大！",
    "堅持就是勝利！",
    "今天的努力，決定明天的高度！",
    "突破極限，超越自我！",
    "每次訓練都是一次進化！",
    "累了就想想為什麼開始！",
    "慢慢來，比較快！",
    "專注當下，享受過程！",
    "強者不是不會累，而是累了也不放棄！",
    "今天練得苦，比賽才輕鬆！",
    "你的對手只有昨天的自己！",
    "一公里一公里，征服全程！",
    "汗水不會騙人！",
    "訓練是送給自己最好的禮物！",
    "每一次呼吸都是力量！",
    "游得更遠，騎得更快，跑得更穩！",
    "心有多大，舞台就有多大！",
    "今天的配速，明天的獎牌！",
    "不怕慢，只怕站！",
    "用行動證明一切！",
    "這就是你想要的人生！",
    "挑戰自己，成為傳奇！",
    "訓練日就是成長日！",
    "把疲憊留在訓練場！",
    "你的毅力正在發光！",
    "每一滴汗都是進步的證明！",
    "鐵人不是天生的，是練出來的！",
    "享受這趟旅程！",
    "今天的你會感謝現在努力的自己！",
    "穩定輸出，持續進步！",
    "把不可能變成可能！",
    "專注、堅持、突破！",
    "訓練越苦，比賽越甜！",
    "你正在書寫自己的故事！",
    "每個早起都值得！",
    "讓身體適應，讓心靈強大！",
    "距離終點又近了一天！",
    "用汗水澆灌夢想！",
    "這條路你不是一個人！",
    "相信訓練，相信自己！",
    "今天也要全力以赴！",
    "累積里程，累積實力！",
    "你的努力終將綻放！",
    "保持節奏，穩健前行！",
    "每一次訓練都是預演！",
    "心肺在變強，意志在成長！",
    "沒有捷徑，只有堅持！",
    "今天的辛苦是明天的資本！",
    "你選擇了不平凡的路！",
    "用速度追逐夢想！",
    "身體會記住每一次訓練！",
    "向著目標，奮力前進！",
    "越練越強，越來越好！",
    "這就是冠軍的日常！",
    "把壓力轉化為動力！",
    "訓練是最好的投資！",
    "每一天都在變強！",
    "讓努力成為習慣！",
    "你的堅持令人敬佩！",
    "終點線在等著你！",
    "今天也是成為更好自己的一天！",
    "用實力說話！",
    "保持飢渴，保持愚蠢！",
    "訓練的意義在於突破！",
    "你已經比昨天更強了！"
];

// Training Schedule Data
export const trainingData = [
    { day: "Week 1 - Day 1 (週一)", status: "No", intensity: "休息", date: "January 12, 2026", swim: "", bike: "", content: "完全休息日，進行輕度伸展和按摩放鬆", hours: 0, type: "完全休息", run: "", week: "Week 1", phase: "建構期" },
    { day: "Week 1 - Day 2 (週二)", status: "No", intensity: "輕鬆", date: "January 13, 2026", swim: "2", bike: "", content: "游泳：技術課 2km (熱身500m + 技術練習1000m + 緩和500m) | 跑步：輕鬆跑 6km", hours: 2, type: "技術課", run: "6", week: "Week 1", phase: "建構期" },
    { day: "Week 1 - Day 3 (週三)", status: "No", intensity: "輕鬆", date: "January 14, 2026", swim: "", bike: "40", content: "自行車：輕鬆騎 40km @ Z2 (65-75% FTP)", hours: 1.5, type: "輕鬆恢復", run: "", week: "Week 1", phase: "建構期" },
    { day: "Week 1 - Day 4 (週四)", status: "No", intensity: "輕鬆", date: "January 15, 2026", swim: "2.5", bike: "", content: "游泳：技術課 2.5km (專注划頻提升) | 跑步：恢復跑 5km", hours: 1.5, type: "技術課, 輕鬆恢復", run: "5", week: "Week 1", phase: "建構期" },
    { day: "Week 1 - Day 5 (週五)", status: "No", intensity: "休息", date: "January 16, 2026", swim: "", bike: "", content: "完全休息日，準備週末長距離訓練", hours: 0, type: "完全休息", run: "", week: "Week 1", phase: "建構期" },
    { day: "Week 1 - Day 6 (週六)", status: "No", intensity: "中等", date: "January 17, 2026", swim: "", bike: "120", content: "自行車：長距離 120km @ Z2 (每30分鐘補給一次)", hours: 4.5, type: "長距離", run: "", week: "Week 1", phase: "建構期" },
    { day: "Week 1 - Day 7 (週日)", status: "No", intensity: "中等", date: "January 18, 2026", swim: "1.5", bike: "", content: "跑步：長跑 18km | 游泳：恢復游 1.5km", hours: 3, type: "輕鬆恢復, 長距離", run: "18", week: "Week 1", phase: "建構期" },
    { day: "Week 2 - Day 1 (週一)", status: "No", intensity: "休息", date: "January 19, 2026", swim: "", bike: "", content: "完全休息日", hours: 0, type: "完全休息", run: "", week: "Week 2", phase: "建構期" },
    { day: "Week 2 - Day 2 (週二)", status: "No", intensity: "輕鬆", date: "January 20, 2026", swim: "2.5", bike: "", content: "游泳：技術課 2.5km (划頻練習) | 跑步：輕鬆跑 7km", hours: 2, type: "技術課, 輕鬆恢復", run: "7", week: "Week 2", phase: "建構期" },
    { day: "Week 2 - Day 3 (週三)", status: "No", intensity: "中等", date: "January 21, 2026", swim: "", bike: "50", content: "自行車：50km (含 3x10分鐘 @ Sweet Spot, 休5分鐘)", hours: 2, type: "配速訓練", run: "", week: "Week 2", phase: "建構期" },
    { day: "Week 2 - Day 4 (週四)", status: "No", intensity: "中等", date: "January 22, 2026", swim: "2", bike: "", content: "游泳：配速訓練 2km (8x200m @ T配速, 休30秒) | 跑步：恢復跑 6km", hours: 2, type: "配速訓練", run: "6", week: "Week 2", phase: "建構期" },
    { day: "Week 2 - Day 5 (週五)", status: "No", intensity: "休息", date: "January 23, 2026", swim: "", bike: "", content: "半休息日，輕度伸展", hours: 0, type: "輕鬆恢復", run: "", week: "Week 2", phase: "建構期" },
    { day: "Week 2 - Day 6 (週六)", status: "No", intensity: "中等", date: "January 24, 2026", swim: "", bike: "130", content: "自行車：長距離 130km @ Z2", hours: 5, type: "長距離", run: "", week: "Week 2", phase: "建構期" },
    { day: "Week 2 - Day 7 (週日)", status: "No", intensity: "中等", date: "January 25, 2026", swim: "2", bike: "", content: "跑步：長跑 20km | 游泳：恢復游 2km", hours: 3.5, type: "輕鬆恢復, 長距離", run: "20", week: "Week 2", phase: "建構期" },
    { day: "Week 3 - Day 1 (週一)", status: "No", intensity: "休息", date: "January 26, 2026", swim: "", bike: "", content: "完全休息日", hours: 0, type: "完全休息", run: "", week: "Week 3", phase: "建構期" },
    { day: "Week 3 - Day 2 (週二)", status: "No", intensity: "輕鬆", date: "January 27, 2026", swim: "2.5", bike: "", content: "游泳：技術課 2.5km | 跑步：輕鬆跑 8km", hours: 2, type: "技術課", run: "8", week: "Week 3", phase: "建構期" },
    { day: "Week 3 - Day 3 (週三)", status: "No", intensity: "中等", date: "January 28, 2026", swim: "", bike: "55", content: "自行車：55km (含 4x10分鐘 @ Sweet Spot)", hours: 2.5, type: "配速訓練", run: "", week: "Week 3", phase: "建構期" },
    { day: "Week 3 - Day 4 (週四)", status: "No", intensity: "高強度", date: "January 29, 2026", swim: "2.5", bike: "", content: "游泳：間歇 2.5km (10x200m @ I配速, 休30秒) | 跑步：輕鬆跑 7km", hours: 2, type: "間歇訓練", run: "7", week: "Week 3", phase: "建構期" },
    { day: "Week 3 - Day 5 (週五)", status: "No", intensity: "休息", date: "January 30, 2026", swim: "", bike: "", content: "完全休息日", hours: 0, type: "完全休息", run: "", week: "Week 3", phase: "建構期" },
    { day: "Week 3 - Day 6 (週六)", status: "No", intensity: "中等", date: "January 31, 2026", swim: "", bike: "135", content: "自行車：長距離 135km @ Z2", hours: 5, type: "長距離", run: "", week: "Week 3", phase: "建構期" },
    { day: "Week 3 - Day 7 (週日)", status: "No", intensity: "中等", date: "February 1, 2026", swim: "2", bike: "", content: "跑步：長跑 21km | 游泳：恢復游 2km", hours: 3.5, type: "輕鬆恢復, 長距離", run: "21", week: "Week 3", phase: "建構期" },
    { day: "Week 4 - Day 1 (週一)", status: "No", intensity: "休息", date: "February 2, 2026", swim: "", bike: "", content: "完全休息日", hours: 0, type: "完全休息", run: "", week: "Week 4", phase: "建構期" },
    { day: "Week 4 - Day 2 (週二)", status: "No", intensity: "輕鬆", date: "February 3, 2026", swim: "3", bike: "", content: "游泳：技術課 3km (划頻70+ SPM) | 跑步：輕鬆跑 8km", hours: 2.5, type: "技術課", run: "8", week: "Week 4", phase: "建構期" },
    { day: "Week 4 - Day 3 (週三)", status: "No", intensity: "中等", date: "February 4, 2026", swim: "", bike: "60", content: "自行車：60km (含 4x12分鐘 @ Sweet Spot)", hours: 2.5, type: "配速訓練", run: "", week: "Week 4", phase: "建構期" },
    { day: "Week 4 - Day 4 (週四)", status: "No", intensity: "中等", date: "February 5, 2026", swim: "2.5", bike: "", content: "游泳：配速 2.5km (6x300m @ T配速) | 跑步：輕鬆跑 7km", hours: 2, type: "配速訓練", run: "7", week: "Week 4", phase: "建構期" },
    { day: "Week 4 - Day 5 (週五)", status: "No", intensity: "休息", date: "February 6, 2026", swim: "", bike: "", content: "完全休息日", hours: 0, type: "完全休息", run: "", week: "Week 4", phase: "建構期" },
    { day: "Week 4 - Day 6 (週六)", status: "No", intensity: "中等", date: "February 7, 2026", swim: "", bike: "140", content: "自行車：長距離 140km @ Z2 (含20分鐘FTP測試)", hours: 5.5, type: "測試, 長距離", run: "", week: "Week 4", phase: "建構期" },
    { day: "Week 4 - Day 7 (週日)", status: "No", intensity: "中等", date: "February 8, 2026", swim: "2.5", bike: "", content: "跑步：長跑 22km (含3km測試配速) | 游泳：測試 2.5km @ 目標配速", hours: 4, type: "測試, 長距離", run: "22", week: "Week 4", phase: "建構期" },
    { day: "Week 5 - Day 1 (週一)", status: "No", intensity: "休息", date: "February 9, 2026", swim: "", bike: "", content: "完全休息日", hours: 0, type: "完全休息", run: "", week: "Week 5", phase: "強化期" },
    { day: "Week 5 - Day 2 (週二)", status: "No", intensity: "中等", date: "February 10, 2026", swim: "3", bike: "", content: "游泳：配速訓練 3km (6x400m @ T配速, 休30秒) | 跑步：輕鬆跑 8km", hours: 2.5, type: "配速訓練", run: "8", week: "Week 5", phase: "強化期" },
    { day: "Week 5 - Day 3 (週三)", status: "No", intensity: "高強度", date: "February 11, 2026", swim: "", bike: "70", content: "自行車：70km (含 3x20分鐘 @ Sweet Spot, 休5分鐘)", hours: 3, type: "配速訓練", run: "", week: "Week 5", phase: "強化期" },
    { day: "Week 5 - Day 4 (週四)", status: "No", intensity: "高強度", date: "February 12, 2026", swim: "3", bike: "", content: "游泳：間歇 3km (10x250m @ I配速, 休30秒) | 跑步：節奏跑 10km (熱身3km + 5km @ T配速 + 緩和2km)", hours: 2.5, type: "間歇訓練", run: "10", week: "Week 5", phase: "強化期" },
    { day: "Week 5 - Day 5 (週五)", status: "No", intensity: "休息", date: "February 13, 2026", swim: "", bike: "", content: "完全休息日，準備週末大訓練量", hours: 0, type: "完全休息", run: "", week: "Week 5", phase: "強化期" },
    { day: "Week 5 - Day 6 (週六)", status: "No", intensity: "高強度", date: "February 14, 2026", swim: "", bike: "160", content: "自行車：長距離 160km @ Z2 | 磚式訓練：接續跑 8km @ M配速", hours: 7, type: "磚式訓練, 長距離", run: "8", week: "Week 5", phase: "強化期" },
    { day: "Week 5 - Day 7 (週日)", status: "No", intensity: "中等", date: "February 15, 2026", swim: "3", bike: "", content: "跑步：長跑 25km (前10km輕鬆 + 中段10km @ M配速 + 最後5km輕鬆) | 游泳：恢復游 3km", hours: 4.5, type: "配速訓練, 長距離", run: "25", week: "Week 5", phase: "強化期" },
    { day: "Week 6 - Day 1 (週一)", status: "No", intensity: "休息", date: "February 16, 2026", swim: "", bike: "", content: "🧧 除夕 | 完全休息日", hours: 0, type: "完全休息", run: "", week: "Week 6", phase: "強化期", holiday: "除夕" },
    { day: "Week 6 - Day 2 (週二)", status: "No", intensity: "中等", date: "February 17, 2026", swim: "3.5", bike: "", content: "🧧 初一 | 游泳：技術+配速 3.5km (1km技術 + 6x300m @ T配速) | 跑步：輕鬆跑 8km", hours: 2.5, type: "技術課, 配速訓練", run: "8", week: "Week 6", phase: "強化期", holiday: "初一" },
    { day: "Week 6 - Day 3 (週三)", status: "No", intensity: "高強度", date: "February 18, 2026", swim: "", bike: "75", content: "🧧 初二 | 自行車：75km (含 4x15分鐘 @ Sweet Spot)", hours: 3, type: "配速訓練", run: "", week: "Week 6", phase: "強化期", holiday: "初二" },
    { day: "Week 6 - Day 4 (週四)", status: "No", intensity: "高強度", date: "February 19, 2026", swim: "3", bike: "", content: "🧧 初三 | 游泳：間歇 3km (8x300m @ I配速, 休40秒) | 跑步：間歇 11km (熱身3km + 8x1km @ I配速 休90秒 + 緩和2km)", hours: 2.5, type: "間歇訓練", run: "11", week: "Week 6", phase: "強化期", holiday: "初三" },
    { day: "Week 6 - Day 5 (週五)", status: "No", intensity: "輕鬆", date: "February 20, 2026", swim: "2", bike: "", content: "🧧 初四 | 游泳：恢復游 2km (輕鬆技術)", hours: 1, type: "輕鬆恢復", run: "", week: "Week 6", phase: "強化期", holiday: "初四" },
    { day: "Week 6 - Day 6 (週六)", status: "No", intensity: "高強度", date: "February 21, 2026", swim: "", bike: "170", content: "🧧 初五 | 自行車：長距離 170km @ Z2 (每30分鐘補給) | 磚式訓練：接續跑 9km @ M配速", hours: 7.5, type: "磚式訓練, 長距離", run: "9", week: "Week 6", phase: "強化期", holiday: "初五" },
    { day: "Week 6 - Day 7 (週日)", status: "No", intensity: "中等", date: "February 22, 2026", swim: "3", bike: "", content: "🧧 初六 | 跑步：長跑 26km (前8km輕鬆 + 中段14km @ M配速 + 最後4km輕鬆) | 游泳：恢復游 3km", hours: 4.5, type: "配速訓練, 長距離", run: "26", week: "Week 6", phase: "強化期", holiday: "初六" },
    { day: "Week 7 - Day 1 (週一)", status: "No", intensity: "休息", date: "February 23, 2026", swim: "", bike: "", content: "完全休息日 - 最大負荷週開始", hours: 0, type: "完全休息", run: "", week: "Week 7", phase: "強化期" },
    { day: "Week 7 - Day 2 (週二)", status: "No", intensity: "高強度", date: "February 24, 2026", swim: "3.5", bike: "", content: "游泳：配速 3.5km (5x500m @ T配速, 休45秒) | 跑步：節奏跑 9km (2km熱身 + 5km @ T配速 + 2km緩和)", hours: 2.5, type: "配速訓練", run: "9", week: "Week 7", phase: "強化期" },
    { day: "Week 7 - Day 3 (週三)", status: "No", intensity: "最大", date: "February 25, 2026", swim: "", bike: "80", content: "自行車：80km (含 3x20分鐘 @ Sweet Spot + 爬坡訓練)", hours: 3.5, type: "配速訓練", run: "", week: "Week 7", phase: "強化期" },
    { day: "Week 7 - Day 4 (週四)", status: "No", intensity: "最大", date: "February 26, 2026", swim: "3.5", bike: "", content: "游泳：間歇 3.5km (12x250m @ I配速, 休30秒) | 跑步：間歇 12km (3km熱身 + 6x1.2km @ I配速 休2分 + 2km緩和)", hours: 3, type: "間歇訓練", run: "12", week: "Week 7", phase: "強化期" },
    { day: "Week 7 - Day 5 (週五)", status: "No", intensity: "輕鬆", date: "February 27, 2026", swim: "2", bike: "", content: "游泳：恢復游 2km | 跑步：輕鬆跑 5km", hours: 1.5, type: "輕鬆恢復", run: "5", week: "Week 7", phase: "強化期" },
    { day: "Week 7 - Day 6 (週六)", status: "No", intensity: "最大", date: "February 28, 2026", swim: "", bike: "180", content: "自行車：長距離 180km @ Z2 (側風訓練) | 磚式訓練：接續跑 10km @ M配速", hours: 8, type: "磚式訓練, 長距離", run: "10", week: "Week 7", phase: "強化期" },
    { day: "Week 7 - Day 7 (週日)", status: "No", intensity: "高強度", date: "March 1, 2026", swim: "3", bike: "", content: "跑步：長跑 28km (前10km輕鬆 + 中段12km @ M配速 + 最後6km維持) | 游泳：恢復游 3km", hours: 5, type: "配速訓練, 長距離", run: "28", week: "Week 7", phase: "強化期" },
    { day: "Week 8 - Day 1 (週一)", status: "No", intensity: "休息", date: "March 2, 2026", swim: "", bike: "", content: "完全休息日 - 恢復週", hours: 0, type: "完全休息", run: "", week: "Week 8", phase: "強化期" },
    { day: "Week 8 - Day 2 (週二)", status: "No", intensity: "輕鬆", date: "March 3, 2026", swim: "3", bike: "", content: "游泳：技術課 3km (專注流線型) | 跑步：輕鬆跑 7km", hours: 2, type: "技術課, 輕鬆恢復", run: "7", week: "Week 8", phase: "強化期" },
    { day: "Week 8 - Day 3 (週三)", status: "No", intensity: "中等", date: "March 4, 2026", swim: "", bike: "65", content: "自行車：65km (含 3x15分鐘 @ Sweet Spot)", hours: 2.5, type: "配速訓練", run: "", week: "Week 8", phase: "強化期" },
    { day: "Week 8 - Day 4 (週四)", status: "No", intensity: "中等", date: "March 5, 2026", swim: "2.5", bike: "", content: "游泳：配速 2.5km (6x350m @ T配速) | 跑步：節奏跑 10km", hours: 2.5, type: "配速訓練", run: "10", week: "Week 8", phase: "強化期" },
    { day: "Week 8 - Day 5 (週五)", status: "No", intensity: "休息", date: "March 6, 2026", swim: "", bike: "", content: "完全休息日", hours: 0, type: "完全休息", run: "", week: "Week 8", phase: "強化期" },
    { day: "Week 8 - Day 6 (週六)", status: "No", intensity: "中等", date: "March 7, 2026", swim: "", bike: "150", content: "自行車：長距離 150km @ Z2 | 磚式訓練：接續跑 8km", hours: 6.5, type: "磚式訓練, 長距離", run: "8", week: "Week 8", phase: "強化期" },
    { day: "Week 8 - Day 7 (週日)", status: "No", intensity: "中等", date: "March 8, 2026", swim: "3", bike: "", content: "跑步：長跑 24km @ 輕鬆配速 | 游泳：恢復游 3km", hours: 4, type: "輕鬆恢復, 長距離", run: "24", week: "Week 8", phase: "強化期" },
    { day: "Week 9 - Day 1 (週一)", status: "No", intensity: "休息", date: "March 9, 2026", swim: "", bike: "", content: "完全休息日", hours: 0, type: "完全休息", run: "", week: "Week 9", phase: "強化期" },
    { day: "Week 9 - Day 2 (週二)", status: "No", intensity: "中等", date: "March 10, 2026", swim: "3.5", bike: "", content: "游泳：配速 3.5km (4x600m @ T配速, 休1分鐘) | 跑步：輕鬆跑 8km", hours: 2.5, type: "配速訓練", run: "8", week: "Week 9", phase: "強化期" },
    { day: "Week 9 - Day 3 (週三)", status: "No", intensity: "高強度", date: "March 11, 2026", swim: "", bike: "75", content: "自行車：75km (含 4x20分鐘 @ Sweet Spot)", hours: 3, type: "配速訓練", run: "", week: "Week 9", phase: "強化期" },
    { day: "Week 9 - Day 4 (週四)", status: "No", intensity: "高強度", date: "March 12, 2026", swim: "3", bike: "", content: "游泳：間歇 3km (10x250m @ I配速) | 跑步：節奏跑 11km (3km + 6km @ T配速 + 2km)", hours: 2.5, type: "間歇訓練", run: "11", week: "Week 9", phase: "強化期" },
    { day: "Week 9 - Day 5 (週五)", status: "No", intensity: "休息", date: "March 13, 2026", swim: "", bike: "", content: "完全休息日，準備週末大訓練", hours: 0, type: "完全休息", run: "", week: "Week 9", phase: "強化期" },
    { day: "Week 9 - Day 6 (週六)", status: "No", intensity: "高強度", date: "March 14, 2026", swim: "", bike: "170", content: "自行車：長距離 170km @ Z2 | 磚式訓練：接續跑 10km @ M配速", hours: 7.5, type: "磚式訓練, 長距離", run: "10", week: "Week 9", phase: "強化期" },
    { day: "Week 9 - Day 7 (週日)", status: "No", intensity: "中等", date: "March 15, 2026", swim: "3", bike: "", content: "跑步：長跑 26km (含 16km @ M配速) | 游泳：恢復游 3km", hours: 4.5, type: "配速訓練, 長距離", run: "26", week: "Week 9", phase: "強化期" },
    { day: "Week 10 - Day 1 (週一)", status: "No", intensity: "休息", date: "March 16, 2026", swim: "", bike: "", content: "完全休息日 - 巔峰期開始", hours: 0, type: "完全休息", run: "", week: "Week 10", phase: "巔峰期" },
    { day: "Week 10 - Day 2 (週二)", status: "No", intensity: "中等", date: "March 17, 2026", swim: "3", bike: "", content: "游泳：技術+配速 3km (1km技術 + 4x400m @ T配速) | 跑步：輕鬆跑 7km", hours: 2, type: "技術課, 配速訓練", run: "7", week: "Week 10", phase: "巔峰期" },
    { day: "Week 10 - Day 3 (週三)", status: "No", intensity: "中等", date: "March 18, 2026", swim: "", bike: "70", content: "自行車：70km (含 3x15分鐘 @ Sweet Spot)", hours: 3, type: "配速訓練", run: "", week: "Week 10", phase: "巔峰期" },
    { day: "Week 10 - Day 4 (週四)", status: "No", intensity: "中等", date: "March 19, 2026", swim: "2.5", bike: "", content: "游泳：配速 2.5km (5x400m @ T配速) | 跑步：節奏跑 10km (2km + 6km @ T配速 + 2km)", hours: 2.5, type: "配速訓練", run: "10", week: "Week 10", phase: "巔峰期" },
    { day: "Week 10 - Day 5 (週五)", status: "No", intensity: "休息", date: "March 20, 2026", swim: "", bike: "", content: "完全休息日，準備週末訓練", hours: 0, type: "完全休息", run: "", week: "Week 10", phase: "巔峰期" },
    { day: "Week 10 - Day 6 (週六)", status: "No", intensity: "中等", date: "March 21, 2026", swim: "", bike: "150", content: "自行車：長距離 150km @ Z2 | 磚式訓練：接續跑 8km @ M配速", hours: 6.5, type: "磚式訓練, 長距離", run: "8", week: "Week 10", phase: "巔峰期" },
    { day: "Week 10 - Day 7 (週日)", status: "No", intensity: "中等", date: "March 22, 2026", swim: "3", bike: "", content: "跑步：長跑 23km (含 15km @ M配速) | 游泳：恢復游 3km", hours: 4, type: "配速訓練, 長距離", run: "23", week: "Week 10", phase: "巔峰期" },
    { day: "Week 11 - Day 1 (週一)", status: "No", intensity: "休息", date: "March 23, 2026", swim: "", bike: "", content: "完全休息日", hours: 0, type: "完全休息", run: "", week: "Week 11", phase: "巔峰期" },
    { day: "Week 11 - Day 2 (週二)", status: "No", intensity: "輕鬆", date: "March 24, 2026", swim: "2.5", bike: "", content: "游泳：技術課 2.5km | 跑步：輕鬆跑 6km", hours: 1.5, type: "技術課, 輕鬆恢復", run: "6", week: "Week 11", phase: "巔峰期" },
    { day: "Week 11 - Day 3 (週三)", status: "No", intensity: "中等", date: "March 25, 2026", swim: "", bike: "60", content: "自行車：60km (含 3x12分鐘 @ Sweet Spot)", hours: 2.5, type: "配速訓練", run: "", week: "Week 11", phase: "巔峰期" },
    { day: "Week 11 - Day 4 (週四)", status: "No", intensity: "中等", date: "March 26, 2026", swim: "2.5", bike: "", content: "游泳：配速 2.5km (6x300m @ T配速) | 跑步：節奏跑 8km", hours: 2, type: "配速訓練", run: "8", week: "Week 11", phase: "巔峰期" },
    { day: "Week 11 - Day 5 (週五)", status: "No", intensity: "休息", date: "March 27, 2026", swim: "", bike: "", content: "完全休息日，準備週末半程模擬賽", hours: 0, type: "完全休息", run: "", week: "Week 11", phase: "巔峰期" },
    { day: "Week 11 - Day 6 (週六)", status: "No", intensity: "輕鬆", date: "March 28, 2026", swim: "", bike: "50", content: "自行車：輕鬆騎 50km @ Z2 | 輕鬆跑 5km", hours: 2.5, type: "輕鬆恢復", run: "5", week: "Week 11", phase: "巔峰期" },
    { day: "Week 11 - Day 7 (週日)", status: "No", intensity: "高強度", date: "March 29, 2026", swim: "2", bike: "90", content: "半程距離模擬賽：游泳 2km (測試配速) + 自行車 90km (測試穩定度) + 跑步 21km (測試配速與補給策略) | 目標：驗證配速與補給計劃", hours: 7, type: "模擬賽", run: "21", week: "Week 11", phase: "巔峰期" },
    { day: "Week 12 - Day 1 (週一)", status: "No", intensity: "休息", date: "March 30, 2026", swim: "", bike: "", content: "完全休息日 - 減量期開始，從模擬賽恢復", hours: 0, type: "完全休息", run: "", week: "Week 12", phase: "減量期" },
    { day: "Week 12 - Day 2 (週二)", status: "No", intensity: "輕鬆", date: "March 31, 2026", swim: "2", bike: "", content: "游泳：技術課 2km (輕鬆恢復) | 跑步：輕鬆跑 6km", hours: 1.5, type: "技術課, 輕鬆恢復", run: "6", week: "Week 12", phase: "減量期" },
    { day: "Week 12 - Day 3 (週三)", status: "No", intensity: "中等", date: "April 1, 2026", swim: "", bike: "50", content: "自行車：50km (含 3x10分鐘 @ Sweet Spot) - 維持品質，減少數量", hours: 2, type: "配速訓練", run: "", week: "Week 12", phase: "減量期" },
    { day: "Week 12 - Day 4 (週四)", status: "No", intensity: "中等", date: "April 2, 2026", swim: "2", bike: "", content: "游泳：配速 2km (5x300m @ T配速) | 跑步：節奏跑 8km (2km + 4km @ T配速 + 2km)", hours: 2, type: "配速訓練", run: "8", week: "Week 12", phase: "減量期" },
    { day: "Week 12 - Day 5 (週五)", status: "No", intensity: "休息", date: "April 3, 2026", swim: "", bike: "", content: "完全休息日", hours: 0, type: "完全休息", run: "", week: "Week 12", phase: "減量期" },
    { day: "Week 12 - Day 6 (週六)", status: "No", intensity: "中等", date: "April 4, 2026", swim: "", bike: "100", content: "自行車：中距離 100km @ Z2 (維持輕鬆) | 磚式訓練：接續跑 6km @ M配速", hours: 4.5, type: "磚式訓練, 配速訓練", run: "6", week: "Week 12", phase: "減量期" },
    { day: "Week 12 - Day 7 (週日)", status: "No", intensity: "輕鬆", date: "April 5, 2026", swim: "2", bike: "", content: "跑步：長跑 15km @ 輕鬆配速 | 游泳：恢復游 2km", hours: 2.5, type: "輕鬆恢復", run: "15", week: "Week 12", phase: "減量期" },
    { day: "Week 13 - Day 1 (週一)", status: "No", intensity: "輕鬆", date: "April 6, 2026", swim: "2", bike: "", content: "游泳：技術課 2km (流線型、手部動作) | 跑步：輕鬆跑 6km", hours: 1.5, type: "技術課, 輕鬆恢復", run: "6", week: "Week 13", phase: "賽前週" },
    { day: "Week 13 - Day 2 (週二)", status: "No", intensity: "輕鬆", date: "April 7, 2026", swim: "", bike: "40", content: "自行車：輕鬆騎 40km @ Z2 (檢查裝備、營養試驗)", hours: 1.5, type: "輕鬆恢復", run: "", week: "Week 13", phase: "賽前週" },
    { day: "Week 13 - Day 3 (週三)", status: "No", intensity: "輕鬆", date: "April 8, 2026", swim: "1.5", bike: "", content: "游泳：開放水域 1.5km (熟悉環境、測試防寒衣) | 跑步：輕鬆跑 4km", hours: 1.5, type: "技術課", run: "4", week: "Week 13", phase: "賽前週" },
    { day: "Week 13 - Day 4 (週四)", status: "No", intensity: "休息", date: "April 9, 2026", swim: "", bike: "", content: "完全休息日 - 保存體力，準備裝備", hours: 0, type: "完全休息", run: "", week: "Week 13", phase: "賽前週" },
    { day: "Week 13 - Day 5 (週五)", status: "No", intensity: "輕鬆", date: "April 10, 2026", swim: "", bike: "20", content: "賽前活化：自行車 20km (含 3x3分鐘 @ M配速) + 跑步 3km (含 3x1分鐘 @ M配速)", hours: 1.5, type: "配速訓練", run: "3", week: "Week 13", phase: "賽前週" },
    { day: "Week 13 - Day 6 (週六)", status: "No", intensity: "休息", date: "April 11, 2026", swim: "", bike: "", content: "完全休息日 - 前往澎湖，營養調整，檢查裝備", hours: 0, type: "完全休息", run: "", week: "Week 13", phase: "賽前週" },
    { day: "Week 13 - Day 7 (週日) - 比賽日", status: "No", intensity: "最大", date: "April 12, 2026", swim: "3.8", bike: "180", content: "🏆 DT Swiss X Ironman 澎湖 2026 🏆 | 目標時間：Sub-12小時 | 游泳 3.8km：1:35:00 | 自行車 180km：6:00:00 | 跑步 42.2km：4:05:00", hours: 12, type: "比賽日", run: "42.2", week: "Week 13", phase: "賽前週" }
];

// Sort by date
trainingData.sort((a, b) => new Date(a.date) - new Date(b.date));

// Get motivation quote for a training day (by index)
export function getMotivationQuote(dayIndex) {
    const training = trainingData[dayIndex];
    if (!training || training.intensity === '休息') return null;

    let trainingDayCount = 0;
    for (let i = 0; i <= dayIndex; i++) {
        if (trainingData[i].intensity !== '休息') {
            trainingDayCount++;
        }
    }
    return motivationQuotes[(trainingDayCount - 1) % motivationQuotes.length];
}
